### ISSUE TITLE
DejaDup backup fails: the 'google-api-python-client' distribution was not found when pydrive backend is used

### ISSUE THREAD

**Issue by pbabinca** [flathub/org.gnome.DejaDup#13]
I have configured DejaDup with pydrive backend and updated to latest version available on flathub (`Commit: 04e9d09bc8d1039c98bd97e74626b7428dbce7fa9830be369460a62c4be4c5ca`, `Subject: Use fixed metainfo commit (dec3b687)`, `Date: 2022-01-01 23:15:27 +0000`). When I click on Backup button I get traceback:

```
Traceback (innermost last):
  File "/app/bin/duplicity", line 87, in <module>
    with_tempdir(main)
  File "/app/bin/duplicity", line 70, in with_tempdir
    fn()
  File "/app/lib/python3.9/site-packages/duplicity/dup_main.py", line 1555, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/app/lib/python3.9/site-packages/duplicity/commandline.py", line 1223, in ProcessCommandLine
    config.backend = backend.get_backend(args[0])
  File "/app/lib/python3.9/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/app/lib/python3.9/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/app/lib/python3.9/site-packages/duplicity/backends/pydrivebackend.py", line 37, in __init__
    from apiclient.discovery import build
  File "/app/lib/python3.9/site-packages/apiclient/__init__.py", line 6, in <module>
    from googleapiclient import discovery
  File "/app/lib/python3.9/site-packages/googleapiclient/discovery.py", line 63, in <module>
    from googleapiclient.http import build_http
  File "/app/lib/python3.9/site-packages/googleapiclient/http.py", line 61, in <module>
    from googleapiclient.model import JsonModel
  File "/app/lib/python3.9/site-packages/googleapiclient/model.py", line 34, in <module>
    _LIBRARY_VERSION = pkg_resources.get_distribution("google-api-python-client").version
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
 pkg_resources.DistributionNotFound: The 'google-api-python-client' distribution was not found and is required by the application
```

---

I downgraded to previous version (`flatpak update --commit=30fb8e290f00fea0ff1e3e89f6749225ee0a3eeabfcbc1de3e2ff06680fe0699 org.gnome.DejaDup`) and clicked on Backup button again. With that version I only get `Failed with an unknown error.`.

---

Only one more version back - `flatpak update --commit=a2194c509ff4808a9db3f99fd5488c3b852aceaaf2a9ff7a97da4ebef3423585 org.gnome.DejaDup` I'm able to backup.

I don't see any error in logs - all of them are successful imports of backends.

---

I understand that packages in this Flatpak are installed from PyPI. Other people within the company are using rpm-installed DejaDup and for that they have packaged https://bugzilla.redhat.com/show_bug.cgi?id=2015282 . Maybe some of those (rpm) deps that are mentioned in the bug are not (pip) installed in the Flatpak?

**Comment by mikix** [comment]
Interesting, and thanks for the report! I can't reproduce myself - am trying to figure out what would be different.

It looks to me like `google-api-python-client` is installed in the flatpak in `/app/lib/python3.9/site-packages/` (the subfolder `googleapiclient`). -- in fact, that is clear from your stacktrace. googleapiclient is trying to find its own version by asking the package manager, but can't.

Looks like that line of code changed upstream, but is not yet in a released version: https://github.com/googleapis/google-api-python-client/commit/83db1d71395e92fb2bd814a31713bd8ba3f412ca#diff-cd2030ce1a6226598d7866b754323086452be4f6c2241d4ac99589d041a016fe

That would probably fix this. But it's not clear to me yet what is actually causing your issue. Why my flatpak can find the version but yours can't. Possibly some pip installation bleeding in from your user (or my user) in a bad way?

**Comment by pbabinca** [comment]
I have tried to build Flatpak on my own but I wasn't successful on either RHEL 8 nor Fedora 35. In both cases `pip3` seemed to try to connect to internet but it failed:
```
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "duplicity" --no-build-isolation
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Looking in links: file:///run/build/python3-duplicity
Processing ./duplicity-0.8.21.post7.tar.gz
  Running command python setup.py egg_info
  /usr/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  /usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a8667e20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a860f070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a8667250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a8946fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a860f2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
  ERROR: No matching distribution found for setuptools_scm
  Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6i47cfab', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-63r7p8_o/duplicity_ff1128acd453429c93c4aaf17d5f5971/setup.py", line 263, in <module>
      setup(name=u"duplicity",
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 154, in setup
      _install_setup_requires(attrs)
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 148, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 771, in resolve
      dist = best[req.key] = env.best_match(
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6i47cfab', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
  Preparing metadata (setup.py) ... error
WARNING: Discarding file:///run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement duplicity (from versions: 0.8.21.post7)
ERROR: No matching distribution found for duplicity
Error: module python3-duplicity: Child process exited with code 1
make: *** [Makefile:8: flatpak] Error 1
```

so I'm not sure what's wrong there

**Comment by mikix** [comment]
Huh odd - it looks like it can't find setuptools_scm - but that is provided in the same exact file as duplicity - look at `duplicity.yaml`

**Comment by pbabinca** [comment]
> Huh odd - it looks like it can't find setuptools_scm - but that is provided in the same exact file as duplicity - look at duplicity.yaml

Yep, I saw that. I'm wondering if you have a clean environment (CI?) where you build those? I might be missing some packages. I thought of `wheel` and `rustc` but neither helped to resolve the issue.

**Comment by mikix** [comment]
Well I build testing packages locally, which is definitely not clean.

But:
- the nightly devel flatpaks are built in gitlab's CI: https://gitlab.gnome.org/World/deja-dup/-/pipelines
-the flathub releases are built on their servers: https://flathub.org/builds/#/apps/org.gnome.DejaDup

So those should both be clean.

**Comment by lugi0** [comment]
I am facing the same issue with a fresh install of the flatpak on a fresh install of Fedora 35
```
[lgiorgi@fedora ~]$ flatpak run org.gnome.DejaDup --version
deja-dup 43.0
```
Furthermore, I cannot restore older backups stored on Google Drive and I only get `Failed with an unknown error.` as the error message

**Comment by mikix** [comment]
OK yes - I can confirm on fresh Fedora 35 and Ubuntu 21.10 installations.  :(  Looking...

**Comment by mikix** [comment]
Interesting. So now the [flathub builder](https://flathub.org/builds/#/builders/12/builds/8733) is running into #14... Will have to address that next.

BTW, this issue (#13) was not appearing for me on my dev machine because of some local use pip packages apparently. I removed all of them, and I was able to reproduce.

So that's another future improvement - make the flatpak ignore local pip.

**Comment by mikix** [comment]
New flatpak release that should fix this was just published on flathub. May take a bit to show up in your updates, though. 

Thanks for the report and help debugging this and #14!

**Comment by pbabinca** [comment]
I can backup with latest version of the tool. Thanks!
