### ISSUE TITLE
Rebuild fails with "Failed to establish a new connection" when attempts to install setuptools_scm

### ISSUE THREAD

**Issue by pbabinca** [flathub/org.gnome.DejaDup#14]
This has been mentioned in #13. Since it is a separate issue I'm opening this one.

I have tried to build Flatpak on my own but I wasn't successful on either RHEL 8 nor Fedora 35. In both cases pip3 seemed to try to connect to internet but it failed:

```
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "duplicity" --no-build-isolation
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Looking in links: file:///run/build/python3-duplicity
Processing ./duplicity-0.8.21.post7.tar.gz
  Running command python setup.py egg_info
  /usr/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  /usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a8667e20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a860f070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a8667250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a8946fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fb3a860f2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
  ERROR: No matching distribution found for setuptools_scm
  Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6i47cfab', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-63r7p8_o/duplicity_ff1128acd453429c93c4aaf17d5f5971/setup.py", line 263, in <module>
      setup(name=u"duplicity",
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 154, in setup
      _install_setup_requires(attrs)
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 148, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 771, in resolve
      dist = best[req.key] = env.best_match(
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6i47cfab', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
  Preparing metadata (setup.py) ... error
WARNING: Discarding file:///run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement duplicity (from versions: 0.8.21.post7)
ERROR: No matching distribution found for duplicity
Error: module python3-duplicity: Child process exited with code 1
make: *** [Makefile:8: flatpak] Error 1
```

---

I have intercepted build (`Ctrl+Z`), entered flatpak (`flatpak enter 723391206 /bin/bash`), entered original CWD (`cd /run/build/python3-duplicity`) and run the same command but with more verbosity:
```
bash-5.1$ /usr/bin/python3 /usr/bin/pip3 install --verbose --verbose --verbose --exists-action=i --no-index --find-links=file:///run/build/python3-duplicity --prefix=/app duplicity --no-build-isolation
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Using pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)
Non-user install due to --prefix or --target option
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-cm_km685
Created temporary directory: /tmp/pip-req-tracker-5yvi46eo
Initialized build tracking at /tmp/pip-req-tracker-5yvi46eo
Created build tracker: /tmp/pip-req-tracker-5yvi46eo
Entered build tracker: /tmp/pip-req-tracker-5yvi46eo
Created temporary directory: /tmp/pip-install-14b0ndv9
Looking in links: file:///run/build/python3-duplicity
0 location(s) to search for versions of duplicity:
Skipping link: Missing project version for duplicity: file:///run/build/python3-duplicity/future-0.18.2.tar.gz
Skipping link: wrong project name (not duplicity): file:///run/build/python3-duplicity/fasteners-0.16.3-py2.py3-none-any.whl
Found link file:///run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz, version: 0.8.21.post7
Local files found: /run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz
Given no hashes to check 1 links for project 'duplicity': discarding no candidates
Processing ./duplicity-0.8.21.post7.tar.gz
  Added duplicity from file:///run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz to build tracker '/tmp/pip-req-tracker-5yvi46eo'
  Running setup.py (path:/tmp/pip-install-14b0ndv9/duplicity_2017d9ecc5c64552964fab134ecef83a/setup.py) egg_info for package duplicity
  Created temporary directory: /tmp/pip-pip-egg-info-xbi62wmd
  Running command python setup.py egg_info
  /usr/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  /usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
    warnings.warn("Setuptools is replacing distutils.")
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbdfc706940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbdfc7064f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbdfc7060a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbdfc6ad1c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fbdfc6ad370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/setuptools-scm/
  ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
  ERROR: No matching distribution found for setuptools_scm
  Traceback (most recent call last):
    File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp21h1fg_b', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-14b0ndv9/duplicity_2017d9ecc5c64552964fab134ecef83a/setup.py", line 263, in <module>
      setup(name=u"duplicity",
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 154, in setup
      _install_setup_requires(attrs)
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 148, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 771, in resolve
      dist = best[req.key] = env.best_match(
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1056, in best_match
      return self.obtain(req, installer)
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1068, in obtain
      return installer(requirement)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp21h1fg_b', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
  Unable to get SCM version: defaulting to 0.8.21.post
  Preparing metadata (setup.py) ... error
WARNING: Discarding file:///run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement duplicity (from versions: 0.8.21.post7)
ERROR: No matching distribution found for duplicity
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('duplicity')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 351, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('duplicity'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for duplicity
Removed duplicity from file:///run/build/python3-duplicity/duplicity-0.8.21.post7.tar.gz from build tracker '/tmp/pip-req-tracker-5yvi46eo'
Removed build tracker: '/tmp/pip-req-tracker-5yvi46eo'
bash-5.1$ 
```

----

I've managed to build Flatpak from CI image:
```
podman run --rm --privileged -ti registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master bash
git clone https://gitlab.gnome.org/World/deja-dup.git
cd ./deja-dup/
rewrite-flatpak-manifest flatpak/org.gnome.DejaDupDevel.yaml deja-dup
flatpak-builder --user --disable-rofiles-fuse flatpak_app --repo=repo flatpak/org.gnome.DejaDupDevel.yaml
```

And later I ran the build again and with similar technique I have intercepted build.

From what I see there are slight differences between build environments. I _guess_ major one is `setuptools` (`python3 -c 'import setuptools.version; print(setuptools.version.__version__)'`) - my local environment, for which build fails is `60.2.0` whereas CI image uses `57.4.0`.

**Comment by mikix** [comment]
OK, if you roll back the Sdk flatpak one commit (to Dec 9), builds work again:

```
flatpak update --commit=13610dcd6bdad52462f9b5112fb8b3b86c7a639e60a2f6784e25849e1dcad95d org.gnome.Sdk//41
```

It got updated on Jan 3, which switched setuptools from 58.0.4 to 60.2.0.

Still don't know what the right fix is, but that at least explains how this started.

**Comment by mikix** [comment]
OK, I think asking setuptools to use pre-60.0.0 behavior works (with `SETUPTOOLS_USE_DISTUTILS=stdlib`): https://github.com/flathub/org.gnome.DejaDup/commit/fef353f08e3f0a3d35ce635e62d0f9ad87825593

**Comment by mikix** [comment]
Yeah that seems to have worked. Marking this closed. (Fixed here and for the nightly build in main repo)

**Comment by pbabinca** [comment]
I'm now able to rebuild the Flatpak from RHEL 8. That might be handy if I got into other issues in the future. Thanks!
